Models/Crop.cs
namespace CropsAppMVC.Models;

public partial class Crop
{
    public int Id { get; set; }

    public string CropName { get; set; }

    public int? CropYield { get; set; }

    public double? CropExpenses { get; set; }

    public double? CropIncome { get; set; }
}

Models/CropDatabaseContext.cs
using Microsoft.EntityFrameworkCore;

namespace CropsAppMVC.Models;

public partial class CropDatabaseContext : DbContext
{
    public CropDatabaseContext()
    {
    }

    public CropDatabaseContext(DbContextOptions<CropDatabaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Crop> Crops { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Server=st10083511server.database.windows.net;Initial Catalog=CropDatabase;Persist Security Info=False;User ID=st10083511;Password=CropPassword123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Crop>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Crops__3214EC0729AABA17");

            entity.Property(e => e.CropName).HasMaxLength(255);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

Models/ErrorViewModel.cs
namespace CropsAppMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CropsController.cs
using CropsAppMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CropsAppMVC.Controllers
{
    public class CropsController : Controller
    {
        private readonly CropDatabaseContext _context;

        public CropsController(CropDatabaseContext context)
        {
            _context = context;
        }

        // GET: Crops
        public async Task<IActionResult> Index()
        {
              return _context.Crops != null ? 
                          View(await _context.Crops.ToListAsync()) :
                          Problem("Entity set 'CropDatabaseContext.Crops'  is null.");
        }

        // GET: Crops/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Crops == null)
            {
                return NotFound();
            }

            var crop = await _context.Crops
                .FirstOrDefaultAsync(m => m.Id == id);
            if (crop == null)
            {
                return NotFound();
            }

            return View(crop);
        }

        // GET: Crops/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Crops/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CropName,CropYield,CropExpenses,CropIncome")] Crop crop)
        {
            if (ModelState.IsValid)
            {
                _context.Add(crop);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(crop);
        }

        // GET: Crops/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Crops == null)
            {
                return NotFound();
            }

            var crop = await _context.Crops.FindAsync(id);
            if (crop == null)
            {
                return NotFound();
            }
            return View(crop);
        }

        // POST: Crops/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CropName,CropYield,CropExpenses,CropIncome")] Crop crop)
        {
            if (id != crop.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(crop);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CropExists(crop.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(crop);
        }

        // GET: Crops/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Crops == null)
            {
                return NotFound();
            }

            var crop = await _context.Crops
                .FirstOrDefaultAsync(m => m.Id == id);
            if (crop == null)
            {
                return NotFound();
            }

            return View(crop);
        }

        // POST: Crops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Crops == null)
            {
                return Problem("Entity set 'CropDatabaseContext.Crops'  is null.");
            }
            var crop = await _context.Crops.FindAsync(id);
            if (crop != null)
            {
                _context.Crops.Remove(crop);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CropExists(int id)
        {
          return (_context.Crops?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/HomeController.cs
using CropsAppMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CropsAppMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Crops/Create.cshtml
@model CropsAppMVC.Models.Crop

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Crop</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CropName" class="control-label"></label>
                <input asp-for="CropName" class="form-control" />
                <span asp-validation-for="CropName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CropYield" class="control-label"></label>
                <input asp-for="CropYield" class="form-control" />
                <span asp-validation-for="CropYield" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CropExpenses" class="control-label"></label>
                <input asp-for="CropExpenses" class="form-control" />
                <span asp-validation-for="CropExpenses" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CropIncome" class="control-label"></label>
                <input asp-for="CropIncome" class="form-control" />
                <span asp-validation-for="CropIncome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Crops/Delete.cshtml
@model CropsAppMVC.Models.Crop

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Crop</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CropName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CropName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CropYield)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CropYield)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CropExpenses)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CropExpenses)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CropIncome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CropIncome)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Crops/Details.cshtml
@model CropsAppMVC.Models.Crop

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Crop</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CropName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CropName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CropYield)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CropYield)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CropExpenses)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CropExpenses)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CropIncome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CropIncome)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Crops/Edit.cshtml
@model CropsAppMVC.Models.Crop

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Crop</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CropName" class="control-label"></label>
                <input asp-for="CropName" class="form-control" />
                <span asp-validation-for="CropName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CropYield" class="control-label"></label>
                <input asp-for="CropYield" class="form-control" />
                <span asp-validation-for="CropYield" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CropExpenses" class="control-label"></label>
                <input asp-for="CropExpenses" class="form-control" />
                <span asp-validation-for="CropExpenses" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CropIncome" class="control-label"></label>
                <input asp-for="CropIncome" class="form-control" />
                <span asp-validation-for="CropIncome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Crops/Index.cshtml
@model IEnumerable<CropsAppMVC.Models.Crop>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
@{
    int? totalyield = 0;
    double? totalExpenses = 0;
    double? totalIncome = 0;
}
<table class="table">
    <thead>
        <tr>
            <th>
                Crop
            </th>
            <th>
                Yield
            </th>
            <th>
                Expenses
            </th>
            <th>
                Income
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

@foreach (var item in Model) {
            totalyield += item.CropYield;
            totalExpenses += item.CropExpenses;
            totalIncome += item.CropIncome;
            <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CropName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CropYield)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CropExpenses)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CropIncome)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<br/>
<div style="text-align: center">
<div style="text-align:center; display:inline-block; width: 25%; background-color: #F1F1F1; padding: 10px; border-radius: 10px; margin-inline: 20px">
    <h6>Total Yield</h6>
    <br />
    <h3>@totalyield</h3>
</div>

<div style="text-align:center; display:inline-block; width: 25%; background-color: #F1F1F1; padding: 10px; border-radius: 10px; margin-inline: 20px">
    <h6>Total Expenses</h6>
    <br />
    <h3>@totalExpenses</h3>
</div>

<div style="text-align:center; display:inline-block; width: 25%; background-color: #F1F1F1; padding: 10px; border-radius: 10px; margin-inline: 20px">
    <h6>Total Income</h6>
    <br />
    <h4>@totalIncome</h4>
</div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome To Cropometer</h1>
    <h4>crops and stuff...</h4>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CropsAppMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CropsAppMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cropometer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Crops" asp-action="Index">Crops</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Cropometer - Jishen Harilal | Evan Teague | Cayde Brummer
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>